### ISSUE TITLE
Different data encodings and text pre-processing

### ISSUE THREAD

**Issue by andreassot10** [CDU-data-science-team/positive_about_change_text_mining#7]
Data from different trusts have different data encodings, causing the data pre-processing in `factory_data_prepros()` to throw an error:

`TypeError: expected string or bytes-like object`

I've found a temp fix [here](https://stackoverflow.com/questions/35937771/typeerror-expected-string-or-bytes-like-object), which I've applied to the code (8f649ed04b72a190d49cb21723a0c54e0d4796c7).

Not entirely confident what's going on and whether this fix is all that's needed. I'll have to investigate further.

**Comment by ChrisBeeley** [comment]
Of course, my fault. Bloody Excel. Should be relatively easy to sort. Let's chat on Monday

**Comment by ChrisBeeley** [comment]
Pretty sure this is fixed now in the data, closing
