### ISSUE TITLE
Place the inputs and outputs of this work into a DB

### ISSUE THREAD

**Issue by ChrisBeeley** [CDU-data-science-team/positive_about_change_text_mining#9]
The inputs and outputs of the text mining need to be accessible from a DB.

**Comment by andreassot10** [comment]
1. Have you seen 81ebeac56e54d1cd92cbdd1b4ff8e2b4e6833754, d8642412742b2f60e8631a5bd66106f3c0f8007c & 3d282c413d83cef54f395ee38dfe130f3de7b22b?
2. As with https://github.com/CDU-data-science-team/experiencesdashboard/issues/31, the sentiment analysis will indeed come from the DB itself. It's on my list of my to dos in the next week or so.

**Comment by ChrisBeeley** [comment]
Good to know 👍
